services:
  - type: web
    name: miki-ai-voice-assistant
    env: node
    plan: free
    rootDir: aria-pro
    buildCommand: npm install && npm run build
    startCommand: npm run start:server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
